name = "data-collector-api"
compatibility_date = "2024-06-20"
pages_build_output_dir = "frontend"

[[d1_databases]]
binding = "DB"
database_name = "fund-rating-db"
database_id = "placeholder-to-be-replaced"
